
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  sensor:
    - state_topic: "sensor/topic"
      unit_of_measurement: '°C'
      name: "thermal sensor"
      device_class: temperature
      force_update: true
      value_template: "{{ value_json.temperature }}"